const NUM_WITNESSES = 436;
const NUM_CASES = 197;
const NUM_DEFENDANTS = 296;
const NUM_CONTACTS = 497;
const NUM_COMMS = NUM_WITNESSES * 4;
const NUM_TASKS = Math.round(NUM_WITNESSES * 0.1);

const PERCENTAGE_VICTIMS = 0.4;

export {
  NUM_WITNESSES,
  NUM_CASES,
  NUM_DEFENDANTS,
  PERCENTAGE_VICTIMS,
  NUM_CONTACTS,
  NUM_COMMS,
  NUM_TASKS,
};
